version: '3'

services:
  app:
    build: .
    entrypoint: .docker/entrypoints.sh
    container_name: achapromo-app
    ports:
      - '3333:3333'
    volumes:
      - .:/home/node/app
    depends_on:
      - db
  db:
    build: .docker/postgres
    container_name: achapromo-db
    restart: always
    tty: true
    ports:
      - '5432:5432'
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=achapromo
